# Generated by Django 3.0.7 on 2020-07-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_friendly_name',
            field=models.CharField(default='Default', max_length=254),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='default', max_length=254),
        ),
    ]
