# Generated by Django 3.0.7 on 2020-07-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('colour_1', models.CharField(max_length=6)),
                ('colour_2', models.CharField(max_length=6)),
                ('colour_3', models.CharField(max_length=6)),
                ('colour_4', models.CharField(max_length=6)),
                ('colour_5', models.CharField(max_length=6)),
            ],
        ),
    ]
