# Generated by Django 3.0.7 on 2020-07-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='dark_mode_background_colour',
            field=models.CharField(default='1c1c1c2', max_length=6),
        ),
    ]
