# Generated by Django 3.0.7 on 2020-07-24 04:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_auto_20200721_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='colour_1',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='theme',
            name='colour_2',
            field=colorfield.fields.ColorField(default='#FFFF00', max_length=18),
        ),
        migrations.AlterField(
            model_name='theme',
            name='colour_3',
            field=colorfield.fields.ColorField(default='#00FF00', max_length=18),
        ),
        migrations.AlterField(
            model_name='theme',
            name='colour_4',
            field=colorfield.fields.ColorField(default='#FF00FF', max_length=18),
        ),
        migrations.AlterField(
            model_name='theme',
            name='colour_5',
            field=colorfield.fields.ColorField(default='#0000FF', max_length=18),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dark_mode_background_colour',
            field=colorfield.fields.ColorField(default='#1c1c1c', max_length=18),
        ),
    ]
