# Generated by Django 3.0.7 on 2020-06-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200624_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu_header_url',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
