# Generated by Django 3.0.7 on 2020-06-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_category_menu_header_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='info_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
