# Generated by Django 3.0.7 on 2020-07-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_allergen_info_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
