# Generated by Django 3.0.7 on 2020-07-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20200720_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='menu_header_url',
        ),
    ]
